快速创建数组

In [2]:
import numpy as np

In [3]:
np.random.randn(8)

array([ 0.42213782, -0.47666836,  0.60125906, -0.45412032, -1.35308299,
        1.68014489,  0.54968618,  0.43634018])

In [8]:
np.random.randint(100,size=(3,3))

array([[22, 59, 18],
       [38, 55, 45],
       [35, 67, 63]])

In [10]:
np.random.randint(10,size=6).reshape(2,3)

array([[1, 5, 4],
       [2, 7, 5]])

数组运算

In [11]:
a=np.random.randint(10,size=6).reshape(2,3)

In [12]:
b=np.random.randint(10,size=6).reshape(2,3)

In [20]:
a

array([[5, 2, 8],
       [2, 3, 7]])

In [19]:
b

array([[2, 3, 9],
       [3, 9, 8]])

In [17]:
a+b

array([[ 7,  5, 17],
       [ 5, 12, 15]])

In [21]:
a-b

array([[ 3, -1, -1],
       [-1, -6, -1]])

In [22]:
a*b

array([[10,  6, 72],
       [ 6, 27, 56]])

In [23]:
a/b

array([[2.5       , 0.66666667, 0.88888889],
       [0.66666667, 0.33333333, 0.875     ]])

创建矩阵

In [24]:
np.mat([[1,2,3],[7,8,9]])

matrix([[1, 2, 3],
        [7, 8, 9]])

In [25]:
np.mat(a)

matrix([[5, 2, 8],
        [2, 3, 7]])

矩阵的运算

In [26]:
A=np.mat(a)

In [27]:
B=np.mat(b)

In [28]:
A

matrix([[5, 2, 8],
        [2, 3, 7]])

In [29]:
B

matrix([[2, 3, 9],
        [3, 9, 8]])

In [30]:
A+B

matrix([[ 7,  5, 17],
        [ 5, 12, 15]])

In [31]:
A-B

matrix([[ 3, -1, -1],
        [-1, -6, -1]])

In [33]:
a=np.mat(np.random.randint(10,size=6).reshape(2,3))
b=np.mat(np.random.randint(10,size=6).reshape(3,2))

In [34]:
a

matrix([[6, 5, 0],
        [0, 6, 2]])

In [35]:
b

matrix([[6, 9],
        [6, 9],
        [3, 7]])

#矩阵相乘必须是双方行列数互换后对应，如a是2*3，b就要3*2

In [36]:
a*b

matrix([[66, 99],
        [42, 68]])

array常用函数

In [37]:
c=np.random.randint(10,size=42).reshape(7,6)

In [38]:
np.unique(c)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
c

array([[4, 1, 8, 8, 3, 6],
       [3, 0, 0, 7, 8, 2],
       [1, 8, 0, 7, 7, 3],
       [3, 8, 5, 9, 7, 1],
       [4, 6, 2, 2, 7, 2],
       [0, 7, 8, 6, 6, 6],
       [4, 5, 7, 0, 3, 8]])

列求和

In [41]:
sum(c)

array([19, 35, 30, 39, 41, 28])

第二行求和

In [44]:
sum(c[1])

20

第二列求和

In [55]:
sum(c[:,1])

35

求最大/小值

In [56]:
c.max()

9

In [57]:
c.min()

0

In [61]:
max(c[3])     #第四行最大值

9

In [67]:
max(c[:,3])   #第4列最大值

9