numpy中自带的input和output

In [ ]:
import pickle

In [1]:
import numpy as np

In [2]:
x=np.arange(20)

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
#f=open('x.pkl','wb')

In [ ]:
#pickle.dump(x,f)

In [29]:
!ls

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


写入硬盘

In [33]:
np.save('one_array',x)

In [37]:
!ls

 驱动器 C 中的卷没有标签。
 卷的序列号是 0C76-B7D6

 C:\Users\HHH 的目录

2022/05/29  23:13    <DIR>          .
2022/05/29  23:13    <DIR>          ..
2021/05/19  22:18    <DIR>          .android
2021/09/27  21:34    <DIR>          .astropy
2022/05/17  22:12    <DIR>          .InstallAnywhere
2022/05/29  21:50    <DIR>          .ipynb_checkpoints
2021/09/30  23:36    <DIR>          .ipython
2022/05/28  23:15    <DIR>          .jupyter
2021/09/27  21:37    <DIR>          .matplotlib
2021/09/30  23:37    <DIR>          .spyder-py3
2022/05/29  22:17               208 11.npy
2021/05/17  22:54    <DIR>          3D Objects
2021/08/07  23:25         2,711,832 AMD_RyzenMaster.log
2021/08/07  23:25             3,835 AMDRM_Install.log
2021/08/25  23:01    <DIR>          ansel
2022/05/29  23:13             2,390 array的input和output-5.29.ipynb
2021/11/18  16:29    <DIR>          Autodesk
2021/05/17  22:54    <DIR>          Contacts
2022/05/29  16:25    <DIR>          Desktop
2022/05/24  21:24    <DIR>          Documen

加载刚才保存的array

In [39]:
np.load('one_array.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
y=np.arange(6)

In [41]:
y

array([0, 1, 2, 3, 4, 5])

压缩保存2个array

In [42]:
np.savez('two_array.npz',a=x,b=y)

In [43]:
ls

 驱动器 C 中的卷没有标签。
 卷的序列号是 0C76-B7D6

 C:\Users\HHH 的目录

2022/05/29  23:23    <DIR>          .
2022/05/29  23:23    <DIR>          ..
2021/05/19  22:18    <DIR>          .android
2021/09/27  21:34    <DIR>          .astropy
2022/05/17  22:12    <DIR>          .InstallAnywhere
2022/05/29  21:50    <DIR>          .ipynb_checkpoints
2021/09/30  23:36    <DIR>          .ipython
2022/05/28  23:15    <DIR>          .jupyter
2021/09/27  21:37    <DIR>          .matplotlib
2021/09/30  23:37    <DIR>          .spyder-py3
2022/05/29  22:17               208 11.npy
2021/05/17  22:54    <DIR>          3D Objects
2021/08/07  23:25         2,711,832 AMD_RyzenMaster.log
2021/08/07  23:25             3,835 AMDRM_Install.log
2021/08/25  23:01    <DIR>          ansel
2022/05/29  23:21             6,199 array的input和output-5.29.ipynb
2021/11/18  16:29    <DIR>          Autodesk
2021/05/17  22:54    <DIR>          Contacts
2022/05/29  16:25    <DIR>          Desktop
2022/05/24  21:24    <DIR>          Documen

加载压缩的2个array

In [44]:
c=np.load('two_array.npz')

In [47]:
c['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
c['b']

array([0, 1, 2, 3, 4, 5])