In [1]:
import numpy as np
import pandas as pd 

 通过python的list创建pandas_series

In [2]:
s1= pd.Series([1,2,3,4])     #此处S大写

In [3]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
s1.values

array([1, 2, 3, 4], dtype=int64)

In [5]:
s1.index

RangeIndex(start=0, stop=4, step=1)

通过np.array创建

In [6]:
s2=pd.Series(np.arange(6))

In [7]:
s2

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int32

通过python字典创建

In [8]:
s3=pd.Series({'1':1,'2':2,'3':3})

In [9]:
s3

1    1
2    2
3    3
dtype: int64

In [10]:
s3.values

array([1, 2, 3], dtype=int64)

In [11]:
s3.index

Index(['1', '2', '3'], dtype='object')

In [12]:
s4=pd.Series([3,6,9,2,5,8],index=['S','T','A','T','Y','T'])    #再用S4举例说明

In [13]:
s4

S    3
T    6
A    9
T    2
Y    5
T    8
dtype: int64

In [14]:
s4.values

array([3, 6, 9, 2, 5, 8], dtype=int64)

In [15]:
s4.index

Index(['S', 'T', 'A', 'T', 'Y', 'T'], dtype='object')

#对series进行操作

In [16]:
s4['T']

T    6
T    2
T    8
dtype: int64

In [17]:
s4[s4<6]

S    3
T    2
Y    5
dtype: int64

series转换成python字典

In [18]:
s4=pd.Series([3,6,9,2,5,8],index=['1','2','3','4','5','6'])

In [19]:
s4

1    3
2    6
3    9
4    2
5    5
6    8
dtype: int64

In [20]:
s4.to_dict()

{'1': 3, '2': 6, '3': 9, '4': 2, '5': 5, '6': 8}

In [21]:
s4

1    3
2    6
3    9
4    2
5    5
6    8
dtype: int64

In [22]:
s5=pd.Series(s4.to_dict())

In [23]:
s5

1    3
2    6
3    9
4    2
5    5
6    8
dtype: int64

In [24]:
s5.values

array([3, 6, 9, 2, 5, 8], dtype=int64)

In [25]:
s5.index

Index(['1', '2', '3', '4', '5', '6'], dtype='object')

改变index

In [26]:
s5.shape

(6,)

In [27]:
s5 

1    3
2    6
3    9
4    2
5    5
6    8
dtype: int64

In [32]:
type(s5)

pandas.core.series.Series

In [28]:
index_1=['a','b','c','d','e','f']

In [42]:
s6=pd.Series(s5.values,index=index_1)

In [43]:
s6

a    3
b    6
c    9
d    2
e    5
f    8
dtype: int64